### ISSUE TITLE
No option to use native Danbooru download filename? Please add.

### ISSUE THREAD

**Issue by kamikaze00007** [kuanyui/BooruShinshi#4]
Hello. Thank you for making this wonderful tool. It is very helpful and I highly appreciate the ease of use. However, I would like to request a simple update that allows us to just download files (I actually just use this for Danbooru personally), and only use the filename provided by Danbooru itself with a manual download, as it seems more accurate.

E.g.
With this Add-on:
__lee_yena_original_drawn_by_robocap__5970836.jpg
If you manually download the file via Danbooru:
__lee_yena_original_drawn_by_robocap__a7d3564f2063c019d41641acc67b3d60.jpg

I find that the automatic naming from Danbooru works better as it labels the characters better instead of my own manual setting especially when there are multiple characters on the image. Would it be possible to just have a setting where if activated, the tool just downloads the image using the default naming tags Danbooru provides during a manual download?

**Comment by kuanyui** [comment]
1. Your description / described specification was so ambiguous that I still cannot understand what exactly you want to do. 
2. If you just want to download the image in one-click with the original filename provided by the website, please check https://addons.mozilla.org/en-US/firefox/addon/double-click-image-download/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
3. This is totally not "a simple update" because it means to add a exceptional option in settings for only a website, for a very rare requirement which maybe only needed by you.
4. Human life is scared and I've burnt out currently, don't have any motivation nor interest to implement this, please consider fork your version, maybe to make a PR if you think it would be usable for other. Or maybe just create a WebExtension from scratch may be more suitable and easier for your requirement (maybe, after all I cannot 100% sure what exactly you want to do.)

**Comment by kuanyui** [comment]
No response, close.
